<a href="https://colab.research.google.com/github/aleguma/tf-cert/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we are going to cover some of the most fundamental concepts of tensors using Tensorflow

More specifically, we're going to cover:

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular Python functions in Tensorflow)
* Using GPUs with Tensorflow (TPUs)
* Exercises to try for yourself

## Introduction to tensors

In [ ]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)   #what version of TF we are using


2.8.2


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)   #creates a constant tensor from a tensor-like object
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for the number of dimensions)
scalar.ndim   

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of the vector
vector.ndim

1

In [ ]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# Check the dimensions of the matrix
matrix.ndim

2

In [ ]:
# Create a matrix with another dtype
another_matrix = tf.constant([[10., 7.],
                              [7., 10.],
                              [7., 7.]], dtype = tf.float16)  #specify the data type with dtype parameter
another_matrix
# default precision is 32 bit precision
# the concept is: the higher the number of precision, the more exact are the numbers stored in the computer
# they occupy then more space when stored (the higher the precision)

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 7.,  7.]], dtype=float16)>

In [ ]:
# shape gives (rows, columns)
# ndim gives the number of dimensions or rank of the tensor -> matrix is rank-2 tensor
another_matrix.ndim

2

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
# Dimensions of the tensor
tensor.ndim

3

In [ ]:
# In this case is composed of 3 matrices of shape 2 by 3!!! It can be read as this!!
# ALL here before are tensors, of different rank, which some of them specific names such as rank-1 = vector!!

What we have created so far:

* Scalar: a single number
* Vector: a number with direction (e.g., wind speed and direction)
* Matrix: a 2-dimensional array of number
* Tensor: an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

Next...create tensors with tf.Variable!!

### Creating tensors with `tf.Variable`

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

* It is always good to read the documentation of tensorflow in tensorflow.org!!

In [ ]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try change one of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
# How about if we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Let's try change our unchangeable tensor, same change
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

In [ ]:
# tf.Variable tensors can be modified, reassigned values, changed with .assign
# tf.constant tensors cannot be changed, they are immutable


**Note:** Rarely in practice will you need to decide whether to use `tf.constant` or `tf.Variable` to create tensors, as Tensorflow does this for you. However, in doubt, use tf.constant and change it later if needed.

### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers.

In [ ]:
# Used to initialize their weights, in other name, the patterns that they are trying to learn in our data. "Learn the representations in the data (patterns, features, weights)"
# Learning will tweak this representation outputs, tweak this random weights and patterns to better suit the data. 
# We will repeat this with many many examples (so the representations outputs line up better with the desired labeled outputs)

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))   # random values from a normal distribution
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_2 = random_2.uniform(shape=(3, 2))   # random values from a uniform distribution
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [ ]:
random_3 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_3 = random_3.normal(shape=(3, 2))   # random values from a normal distribution
random_3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
# Are random_3 and random_1 equal?
random_3, random_1, random_3 == random_1    # checking if they have the same values!

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [ ]:
# Order of the data can affect how the network learns! If there are 1000 images in a row of the same stuff, it would adjust the weights too much for that image type.
# So it is a good idea to mix up all the image classes so they have random ordering!
# The internal patterns will be adjusted to learn all classes at the same time!

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't affect learning)
not_shuffled = tf.constant([[10, 7],
                            [8, 5],
                            [1, 3]])
not_shuffled.ndim

2

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 8,  5],
       [ 1,  3]], dtype=int32)>

In [ ]:
# Shuffle the non-shuffled tensor (along its first dimension, rows; keeping second dimensions in order!)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 8,  5],
       [10,  7],
       [ 1,  3]], dtype=int32)>

In [ ]:
# Shuffle the non-shuffled tensor (along its first dimension, rows; keeping second dimensions in order!)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 8,  5],
       [ 1,  3]], dtype=int32)>

In [ ]:
# Shuffle the non-shuffled tensor (along its first dimension, rows; keeping second dimensions in order!)
tf.random.set_seed(42)   # global random seed
tf.random.shuffle(not_shuffled, seed = 42)   # operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 8,  5],
       [ 1,  3]], dtype=int32)>

### Check in the documentation on random seed generation!
There is a relation/interaction between the global and the operation level random seed! Check!
https://www.tensorflow.org/api_docs/python/tf/random/set_seed

It looks like if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed:

> Rule 4: If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [ ]:
# Shuffling is done so the patterns that the neural network learns are tuned to all kind of images (classes) throughout the entire training cycle.

In [ ]:
# Practicing with seeds

tf.random.shuffle(not_shuffled, seed=42)   # we get a different order each time

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  3],
       [10,  7],
       [ 8,  5]], dtype=int32)>

In [ ]:
# But if we set the global random seed...
tf.random.set_seed(42)  # global lebel random seed
tf.random.shuffle(not_shuffled, seed=42)   # operation level random seed
# then we have all the times the same, both seeds are used

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 8,  5],
       [ 1,  3]], dtype=int32)>

In [ ]:
# This is useful to make reproducible experiments and get the same results to happen every time, and not a different one each time you run the experiment!

### Other ways to make tensors 


In [ ]:
# Create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a tensor of all zeroes
tf.zeros(shape=(10, 7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into TF tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing). Otherwise they are very similar.


In [ ]:
# You can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) #create a NumPy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix)      # capital letter for matrix or tensor
# y = tf.constant(vector)           # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)   # converting a NumPy array into a TF (column) vector (rank-1 tensor)
A  # unmodified shape, same as original NumPy array shape

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4))   # converting a NumPy array into a TF (rank-3) tensor.
A   # dimensions are 2, 3, 4 (like 2 matrices of size 3 by 4)

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
2 * 3  * 4   # check if the dimensions match the number of objects we have

# NOTE ABOUT SHAPE: if you want to adjust or rearrange the shape of an array/tensor, the new number of dimensions in the shape defining the amount of elements, must add up to have the same number of elements in the original tensor.
# In this example it was 24! Otherwise would make an error. 
# Example below

24

In [ ]:
B = tf.constant(numpy_A, shape=(3, 8))     # they add up to 24, so all good, possible rearrangement!
B

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [ ]:
C = tf.constant(numpy_A, shape=(3, 3, 3))  # they do not add up to 24, so error!!

TypeError: ignored

In [ ]:
# Getting the number of dimensions

A.ndim, B.ndim    # results (number of dimensions of A, number of dimensions of B)

(3, 2)

### Getting information from tensors

When dealing with tensors you probably want to be aware of the following attributes:

* Shape : the lenght (number of elements) of each of the dimensions of a tensor. : `tensor.shape`
* Rank : The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n (where n >= 0). : `tensor.dim`
* Axis or dimension : A particular dimension of a tensor. : `tensor[0]`, `tensor[:, 1]`, ...
* Size : The total number of items in the tensor. : `tf.size(tensor)`

In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor   # 2 elements in the first dimension, composed of 3 elements of the second dimension which are composed of elements of 4 items in the 3rd dimensions and each of these items are composed of 5 elements.

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# You will probably most of your time dealing with lining your shapes of your tensors up.
# When you pass a tensor into a neural network it typically has to be in a certain shape and then the output tensor (i.e., patterns learned by the NN) also hast to be in a certain shape.

In [ ]:
rank_4_tensor[0]   # zeroth element of the tensor; we are indexing onto the first dimension; getting the first element

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)   # (2, 3, 4, 5), 4, 120

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
2 * 3 * 4 * 5

120

In [ ]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy()) # to make it a numpy integer and make it more readable, gets the element itself from the tf.Tensor type

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


### Indexing tensors 

Tensors can be indexed just like Python lists.

In [ ]:
# Get the first 2 elements of each dimension

some_list = [1, 2, 3, 4]
some_list[:2]

rank_4_tensor[:2, :2, :2, :2]  # like a Python list

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension except for the final one

some_list[:1]

rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Previous is equivalent to
rank_4_tensor[:1, :1, :1, :]  # getting all from last dimension (:).

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Get the second last axis
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
# Get second axis
rank_4_tensor[:1, :, :1, :1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [ ]:
# Get first axis
rank_4_tensor[:, :1, :1, :1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [ ]:
# Adding extra dimensions, reshaping!

# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.ones(shape=(3,3)) # one example
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim, rank_2_tensor

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

In [ ]:
# Get the last item of each row of our rank 2 tensor

some_list, some_list[-1]  # getting the last item of a list

rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add in an extra dimension to the tensor (keeping the same info stored in the rank 2), alter the size of the tensor!
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # added a dimension at the end of 1
# ... means on every previous axis of the original tensor, equivalent to [:, :] 
# so in this case is add an axis at the very end, so it means include those axis and add a new one (at the end in this case)
rank_3_tensor


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis

tf.expand_dims(rank_2_tensor, axis= -1 )  # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Expand the 0-axis
tf.expand_dims(rank_2_tensor, axis= 0 )  # 0 means expand the first axis (0-axis), add extra dimension at the front

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis= 1 )  # add the extra dimension in the middle, in this case

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# So the content/numbers inside, the elements stay the same but the number of dimensions change.
# So it changes how these numbers are stored. 

### Manipulating tensors (tensor operations)

Finding patterns in tensors often involve manipulating tensors. In TF, much of the pattern discovery is done for you. However, oftentimes the pattern discovery is through the extended use of a few basic operations.

**Basic operations** (element-wise operations, they are applied to each element of the tensor individually).

`+`, `-`, `*`, `/`

In [ ]:
# You can add values to a tesnor using the addition operator
tensor = tf.constant([[10, 7], 
                      [3, 4]])
tensor + 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Often we do not want to change the original tensor. The only way is to reassign it.
tensor = tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# And subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
# In addition to Python operators we can use equivalent tensorflow functions.
# We can use the tensorflow built-in function too
tf.multiply(tensor, 10)    # alias of tf.math.multiply

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# The benefits of using the TF operations is to speed up the computation on a GPU. Usually that only happens when you use the TF version of some operator.
# Again the original tensor is still unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.add(tensor, 10)  # addition TF function

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

**Matrix multiplication** (tensor multiplication)

In machine learning, matrix multiplication is one of the most common tensor operations.

Matrix multiplication == **dot product**

Check matrixmultiplication.xyz

There are **two** rules our tensors (or matrices) need to fulfill if we're going to matrix multiply them:

1. **The inner dimensions must match**
2. **The result matrix has the shape of the outer dimensions**

In [ ]:
# Matrix multiplication in TensorFlow.
# tf.linalg.matmul == tf.matmul (alias)
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor * tensor   # element-wise multiplication (each element by the corresponding one in the other matrix)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
# Matrix multiplication with Python operator "@"

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# All these operations work because the shapes match for computing the matrix multiplication (in this case they have the same shape)
tensor.shape

TensorShape([2, 2])

In [ ]:
# What if we want to do it using tensors of different shape?
# For example...
# Create  a tensor of (3, 2)
X = tf.constant([[1, 2],
                [3, 4],
                [5, 6]])

# Create another (3, 2) tensor
Y =  tf.constant([[7, 8],
                  [9, 10],
                  [11, 12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Try to matrix multiply tensors of same shape
X @ Y

InvalidArgumentError: ignored

In [ ]:
tf.matmul(X, Y)

InvalidArgumentError: ignored

In [ ]:
# Why we cannot?
# There are 2 rules for matrix multiplication to be performed! (see below)

**Resource** Info and example of matrix multiplication: https://www.mathisfun.com/algebra/matrix-multiplying.html

#### Matrix multiplication is also known as **Dot Product** 

To be possible:

1. Numbers on the inside must match. Ex. (3, **2**) (**2**, 3)
2. Resulting matrix size is the same as the outside numbers. So, (**3**, 2) (2, **3**) = (**3, 3**)

In [ ]:
# Make the previous examples work and perform the dot product!
# Change the sizes of one of the tensors or create a new one with appropriate shapes.

Y # original tensor

# Let's change the shape of Y

tf.reshape(Y, shape=(2, 3))


NameError: ignored

In [ ]:
# Try to matrix multiply X by reshaped Y
X @ tf.reshape(Y, shape=(2, 3))   # it works!


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Why?

X. shape, tf.reshape(Y, shape=(2, 3)).shape   #  Shape of the inner dimensions match, and they actually match

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3))) # it also works! The requirements are met!

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Try reshaping X instead of Y...

tf.matmul(tf.reshape(X, shape=(2, 3)), Y)      # it works! But the output is different!

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
# The resulting matrix has always the dimensions of the outer dimensions of the multiplying matrices!

tf.reshape(X, shape=(2, 3)).shape, Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [ ]:
# So the matrix multiplication works but the output dimensions are different!! That's a very important point!
# So the output will depend on how you manipulate your tensors! 
# We are multiplying the same numbers, but just in different shapes and then the output is different!

**IMPORTANT: We can do the same thing as reshape with Transpose**, but they are different operations and not always interchangeably (may produce different outputs).

**The different is that Transpose flips the axes, whereas Reshape just shuffles around the elements of the tensor to the shape that you want.** 

In [ ]:
# Transpose is an important tensor transformation. 

X, tf.transpose(X), tf.reshape(X, shape=(2, 3))    # the output is different

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X), Y)  # we obtain a different result than when using reshape

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# A lot of work in ML and NN is reshaping the data in the form of tensors to both prepare it to be used with various operations such as feeding into the model and once you get it out of the model to be able to deduce patterns from it and convert it into something human understandable. 

##### A good example of why we multiply tensors this way is here: https://www.mathisfun.com/algebra/matrix-multiplying.html

**The Dot Product**

Matrix multiplication is also referred to as the dot product. 

You can perform matrix multiplication using:

* `tf.matmul()`
* `tf.tensordot()`
* `@` (not TF operation)

In [ ]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Perform the dot product on X and Y (requires ours examples X or Y to be transposed)
# Transposing results in different outputs than reshaping and transposing is flipping the axes, whereas reshaping is just reshuffling.
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))   # provides a different result than using transpose Y!

# A lot of time in applications is focused on reshaping vectors/matrices/tensors into the shape that you want them.

# Transpose and reshape may give different results. They do not necessarily result in the same values, as shown in the example.

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Let's start to make things clear and prettier
# Check the values of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y, "\n") # "\n" is for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, shape=(2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

# One of the most common errors you are going to get in writing NN code is misshaped tensors and it might be a deceiving error. That is when your tensors line up with shape and the outputs works (silent error, alls seems to work) but the results are clearly incorrect.
# So plotting things this way is the best way to investigate these silent errors. Print statements like the ones above, to see what is going on.

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [ ]:
# Most of the times these operations will be done behind the scenes for us, to figure it out different patterns and do the appropriate calculations!
# But is worth to know how to do it and how these operations work!

Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to get satisfy the matrix multiplication rules.

### Changing the datatype of a tensor

In [ ]:
tf.__version__

'2.8.2'

In [ ]:
### Default is 32-bit precision, how to change it if you need it?

# Create a new tensor with default datatype (float32).
# The default value depends on what data is inside the tensor (floats, integer...)

B = tf.constant([1.7, 7.4])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [ ]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [ ]:
# Change from float32 to float16 (reduced precision)
# Precision == bits of memory taken per value (stored size)
# Reduced precision might be faster according to specifications by GPUs (modern accelerators can run operations faster, specialized operations and read faster)

D = tf.cast(B, dtype=tf.float16)   # change data type of B
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# This might matter more when we have millions of elements, it can reduce the stored size significantly.
# We basically halve the amount of memory the tensor occupies, allowing hardware accelerators to make calculations potentially twice as fast.

In [ ]:
# Change from int32 to float32

E = tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

In [ ]:
E_float16 = tf.cast(E, dtype=tf.float16)

In [ ]:
E_float16, E_float16.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>,
 tf.float16)

### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [ ]:
# Get the absolute values (not really agreggation but included for completeness)

D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# Get the absolute values
tf.abs(D) # take the magnitude not the sign of the tensor values

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation:
* Get the minimum of a tensor
* Get the maximum of a tensor
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
# Creating a random tensor with values between 0 and 100 of size 50

E =  tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([95, 21, 52, 93, 52, 56, 53, 91,  0, 96, 27, 41, 74, 23,  4, 66, 55,
       27, 41, 10, 40, 20, 12, 47, 43, 11, 51, 20, 46, 13, 47, 36, 52, 22,
       95,  4,  8, 35, 57, 37, 85, 27,  4, 61, 47, 93, 64, 74, 20, 20])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# Find the minimum of a tensor
# TF puts reduce before their aggregation methods usually
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# Corresponding in NP
np.min(E)

0

In [ ]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=92>

In [ ]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=41>

In [ ]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2062>

In [ ]:
# EXTRA CHALLENGE! Find the variance and standard deviation using TF methods
E = tf.cast(E, dtype=tf.float32)  # changed type to FLOAT otherwise VARIANCE AND STD DEV were giving error with INT

tf.math.reduce_variance(E)  # no shorter alias for it, no reduce_var()


<tf.Tensor: shape=(), dtype=float32, numpy=749.0704>

In [ ]:
tf.math.reduce_std(E)  # no shorter alias for it, no reduce_std()
# E must be type float, otherwise the function does not work with INT type!

<tf.Tensor: shape=(), dtype=float32, numpy=27.36915>

In [ ]:
# Also can be computed using tensorflow_probability library
import tensorflow_probability as tfp

tfp.stats.variance(E)   # E must be type float, otherwise the function does not work with INT type! (i.e., type error)!

<tf.Tensor: shape=(), dtype=float32, numpy=749.0704>

### Find the positional maximum and minimum

Retrieve at what index (position) the max or min values occur.

The representation outputs are usually referred to as prediction probabilities. Each of the positions (index) in the output vector might be associated to a category (labels). So, if we find the largest number of the output vector, then we can know what is the most likely category (index with largest output) of the output.

In [ ]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)   # for reproducibility, to get same numbers every time
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find the positional maximum of F, meaning at which index the maximum value occurs
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
np.argmax(F)

42

In [ ]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Check for equality
assert F[tf.argmax(F)] == tf.reduce_max(F)   # no error, so they are the same!

In [ ]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))   #adding a few single dimensions right to the start.
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
# With squeezing the shape is where we have to focus our attention
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)   # remove
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

In [ ]:
# Squeeze removes dimensions of size 1 from the shape of a tensor (removes single dimensions, get rid of extra dimensions)

### One-hot encoding tensors

It is a form of numerical encoding. Having a 1 (one hot) in a specific position referring to a specific class/value, and 0 for the rest of the elements in the vector.

In [ ]:
# Create a list of indices 
some_list = [0, 1, 2, 3] # could be red, green, blue, purple

#One hot encode our list of indices
tf.one_hot(some_list, depth=len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#Specify custom values for one hot encoding (not of much use in practice)
tf.one_hot(some_list, depth=4, on_value="yo I love deep learning", off_value="I also like to dance")

<tf.Tensor: shape=(4, 5), dtype=string, numpy=
array([[b'yo I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance',
        b'I also like to dance'],
       [b'I also like to dance', b'yo I love deep learning',
        b'I also like to dance', b'I also like to dance',
        b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo I love deep learning', b'I also like to dance',
        b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo I love deep learning',
        b'I also like to dance']], dtype=object)>

In [ ]:
tf.one_hot(some_list, depth=3), tf.one_hot(some_list, depth=5)

(<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]], dtype=float32)>)

### Squaring, log, square root

In [ ]:
# Create a new tensor
H = tf.range(1, 10)  #new way to create a tensor
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Find the square root
#tf.sqrt(H) # will error, method requires non-int datatype
tf.sqrt(tf.cast(H, dtype=tf.float32))   # we need to cast it as it does not work with INTs

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
# Find the log
tf.math.log(tf.cast(H, dtype=tf.float32))    # no alias without math library prefix, and type must be float!

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

NumPy is a fundamental library for any kind of numerical computing in Python and it is all built upon the numpy array.

Tensorflow interacts beautifully with NumPy arrays.

Note: One of the main differences between a Tensorflow tensor and a NumPy array is that a TensorFlow tensor can be run on a GPU or TPU (for faster numerical processing).

In [ ]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# Convert tensor J to a Numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [ ]:
# This is good as sometimes some operations are better or easier using NumPy and sometimes TF, so it is good this interoperability!
# However
# The default types of each are slightly different

numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

# Check the data types of each
numpy_J.dtype, tensor_J.dtype   # different default data types!


(tf.float64, tf.float32)

In [ ]:
# Knowing this is important as some operations require specific data types!
# Depending on how the tensors are created, they might have a different data type!

# One of the main issues you will run into when computing with different tensors is different data types issues.
# So treat this as your heads up!

### Finding access to GPUs

In [ ]:
import tensorflow as tf
# to restart Colab to use GPU (by default uses CPU) go to Runtime -> Change Runtime Type -> GPU (and save)
tf.config.list_physical_devices()   #checking what do we have access

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
tf.config.list_physical_devices("GPU")  #checking if we have access to a GPU

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
# terminal command to check what type of nvidia gpu are we using
!nvidia-smi

Mon Aug  1 15:47:31 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# CUDA is the interface between the GPU and the tensorflow code (an API)

> **Note:** If you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible.

##### We covered the Fundamentals to start the journey with Tensorflow but this is just scratching the surface. There are many many things! This is just a starting point!